server:
  port: 8060
#logging:
#  level:
#    org.springframework.kafka: DEBUG
#    org.apache.kafka: DEBUG
spring:
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:order}
    username: ${DATASOURCE_USERNAME:order}
    password: ${DATASOURCE_PASSWORD:order}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: createOrderMessage:com.juliomesquita.order.infrastructure.broker.kafka.consumer.CreateOrderMessage,updateOrderMessage:com.juliomesquita.order.infrastructure.broker.kafka.consumer.UpdateOrderMessage
#        ,updateOrderMessage:com.juliomesquita.order.infrastructure.broker.kafka.consumer.UpdateOrderMessage
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: createComandaMessage:com.juliomesquita.order.application.usecase.order.create.CreateComandaMessage